dataset_yaml: configs/data_no_dot.yaml

base_model: models/base/yolo11n.pt
trained_model: models/trained/ball_detector_without_dots.pt

project_dir: runs
experiment_name: exp02_yolo11n_without_dots

epochs: 50
imgsz: 640
batch: 4

confidence_threshold: 0.25
iou_threshold: 0.5