dataset_yaml: "data_local.yaml"

base_model: "yolo11n.pt"

project_dir: "runs"
experiment_name: "yolo11n_ball_detection"

epochs: 15
imgsz: 640
batch: 4

confidence_threshold: 0.25
iou_threshold: 0.5

trained_model: "weights/best.pt"